# Generated by Django 3.1.13 on 2021-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexes',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hexes',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
