# Generated by Django 3.1.13 on 2021-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210719_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hexes",
            name="hex",
            field=models.TextField(),
        ),
    ]
