# Generated by Django 3.1.13 on 2021-07-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20210720_1206"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hexes",
            old_name="like",
            new_name="likes",
        ),
        migrations.RenameField(
            model_name="hexes",
            old_name="unlike",
            new_name="unlikes",
        ),
    ]
