# Generated by Django 3.1.13 on 2021-07-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20210720_1302"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hexes",
            old_name="unlikes",
            new_name="dislikes",
        ),
    ]
