name: Verify code (python)
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install black
      - name: Verify code (python w/black)
        run: |
          black --check -t py38 backend/ test/
