name: Verify code (js)
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo npm install -g prettier
      - name: Verify code (js w/prettier)
        run: |
          prettier --check src/
